Remove on master commit check

diff --git a/repository/hooks/pre-commit b/repository/hooks/pre-commit
--- a/repository/hooks/pre-commit
+++ b/repository/hooks/pre-commit
@@ -8,12 +8,12 @@ echo Running git pre-commit hook
 export PATH=/usr/local/bin:$PATH
 
 # Check to see if we are on master branch. Stop accidental commits
-branch=$(git symbolic-ref HEAD 2>/dev/null)
-if [[ ${branch} == "refs/heads/master" ]] || [[ ${branch} == "refs/heads/develop" ]]
-then
-  echo "Cannot commit to $branch branch"
-  exit 1
-fi
+# branch=$(git symbolic-ref HEAD 2>/dev/null)
+# if [[ ${branch} == "refs/heads/master" ]] || [[ ${branch} == "refs/heads/develop" ]]
+# then
+#   echo "Cannot commit to $branch branch"
+#   exit 1
+# fi
 
 repo_root=$(git rev-parse --show-toplevel)
 cd ${repo_root}
